{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "71c840e5",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Copied file to: sample.pptx.pptx\n",
      "Converted sample.pptx.pptx to PDF\n",
      "OCR applied on page 6\n",
      "Saved extracted text: sample.pptx.txt\n",
      "\n",
      "================ DOCUMENT SUMMARY ================\n",
      "\n",
      "Processed on: 2026-01-07 21:12:24\n",
      "File Name: sample.pptx.pptx\n",
      "Directory: D:\\Softoo\\ML Task\\AI_Engine\\documents\\sample.pptx.pptx\n",
      "Total Pages/Rows: 31\n",
      "Status: Document Ready for processing\n",
      "\n",
      "=================================================\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import sys\n",
    "import re\n",
    "import shutil\n",
    "import logging\n",
    "from pathlib import Path\n",
    "from datetime import datetime\n",
    "\n",
    "import PyPDF2\n",
    "import pandas as pd\n",
    "import pytesseract\n",
    "from pdf2image import convert_from_path\n",
    "from PIL import Image\n",
    "from docx2pdf import convert as docx2pdf_convert\n",
    "from pptx import Presentation\n",
    "from reportlab.pdfgen import canvas\n",
    "\n",
    "DOCUMENT_DIR = \"documents\"\n",
    "os.makedirs(DOCUMENT_DIR, exist_ok=True)\n",
    "\n",
    "POPPLER_PATH = r\"C:\\Program Files\\poppler-25.12.0\\Library\\bin\"\n",
    "SAVE_TEXT = True\n",
    "\n",
    "logging.basicConfig(level=logging.INFO, format=\"%(message)s\")\n",
    "\n",
    "\n",
    "def ensure_file(src_path):\n",
    "    src = Path(src_path)\n",
    "    if not src.exists():\n",
    "        raise FileNotFoundError(f\"File not found: {src}\")\n",
    "\n",
    "    dest = Path(DOCUMENT_DIR) / src.name\n",
    "    if dest.exists():\n",
    "        dest = dest.with_name(f\"{dest.stem}_{int(datetime.now().timestamp())}{dest.suffix}\")\n",
    "\n",
    "    shutil.copy(src, dest)\n",
    "    logging.info(f\"Copied file to: {dest.name}\")\n",
    "    return dest\n",
    "\n",
    "\n",
    "def ppt_to_pdf(ppt_path):\n",
    "    ppt = Presentation(ppt_path)\n",
    "    pdf_path = ppt_path.with_suffix(\".pdf\")\n",
    "    c = canvas.Canvas(str(pdf_path))\n",
    "\n",
    "    for slide in ppt.slides:\n",
    "        text = []\n",
    "        for shape in slide.shapes:\n",
    "            if hasattr(shape, \"text\"):\n",
    "                text.append(shape.text)\n",
    "\n",
    "        c.drawString(40, 800, \" \".join(text)[:2000])\n",
    "        c.showPage()\n",
    "\n",
    "    c.save()\n",
    "    logging.info(f\"Converted {ppt_path.name} to PDF\")\n",
    "    return pdf_path\n",
    "\n",
    "\n",
    "def convert_to_pdf(file_path):\n",
    "    ext = file_path.suffix.lower()\n",
    "\n",
    "    if ext == \".pdf\":\n",
    "        return file_path\n",
    "\n",
    "    if ext == \".docx\":\n",
    "        sys.stdout = open(os.devnull, \"w\")\n",
    "        docx2pdf_convert(str(file_path), str(file_path.parent))\n",
    "        sys.stdout = sys.__stdout__\n",
    "        return file_path.with_suffix(\".pdf\")\n",
    "\n",
    "    if ext == \".txt\":\n",
    "        from fpdf import FPDF\n",
    "        pdf_path = file_path.with_suffix(\".pdf\")\n",
    "        pdf = FPDF()\n",
    "        pdf.add_page()\n",
    "        pdf.set_font(\"Arial\", size=12)\n",
    "        with open(file_path, encoding=\"utf-8\") as f:\n",
    "            for line in f:\n",
    "                pdf.multi_cell(0, 6, line)\n",
    "        pdf.output(pdf_path)\n",
    "        return pdf_path\n",
    "\n",
    "    if ext in [\".ppt\", \".pptx\"]:\n",
    "        return ppt_to_pdf(file_path)\n",
    "\n",
    "    raise ValueError(f\"Unsupported file type: {ext}\")\n",
    "\n",
    "\n",
    "def iter_pdf_pages(pdf_path):\n",
    "    reader = PyPDF2.PdfReader(str(pdf_path))\n",
    "\n",
    "    for i, page in enumerate(reader.pages, start=1):\n",
    "        text = page.extract_text() or \"\"\n",
    "\n",
    "        if not text.strip():\n",
    "            logging.info(f\"OCR applied on page {i}\")\n",
    "            images = convert_from_path(\n",
    "                pdf_path,\n",
    "                first_page=i,\n",
    "                last_page=i,\n",
    "                dpi=200,\n",
    "                poppler_path=POPPLER_PATH\n",
    "            )\n",
    "            text = pytesseract.image_to_string(images[0].convert(\"L\"))\n",
    "\n",
    "        text = re.sub(r\"\\s+\", \" \", text).strip()\n",
    "\n",
    "        yield {\n",
    "            \"page_content\": text,\n",
    "            \"metadata\": {\n",
    "                \"file_name\": pdf_path.name,\n",
    "                \"page\": i,\n",
    "                \"type\": \"pdf\"\n",
    "            }\n",
    "        }\n",
    "\n",
    "\n",
    "def load_csv(csv_path):\n",
    "    df = pd.read_csv(csv_path)\n",
    "    docs = []\n",
    "\n",
    "    for i, row in df.iterrows():\n",
    "        docs.append({\n",
    "            \"page_content\": \" | \".join(f\"{k}: {v}\" for k, v in row.items()),\n",
    "            \"metadata\": {\n",
    "                \"file_name\": csv_path.name,\n",
    "                \"row\": i + 1,\n",
    "                \"type\": \"csv\"\n",
    "            }\n",
    "        })\n",
    "\n",
    "    return docs\n",
    "\n",
    "\n",
    "def save_text(name, docs):\n",
    "    if not SAVE_TEXT:\n",
    "        return\n",
    "\n",
    "    txt = Path(DOCUMENT_DIR) / f\"{name}.txt\"\n",
    "    with open(txt, \"w\", encoding=\"utf-8\") as f:\n",
    "        for d in docs:\n",
    "            f.write(d[\"page_content\"] + \"\\n\")\n",
    "\n",
    "    logging.info(f\"Saved extracted text: {txt.name}\")\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    SOURCE_FILE = r\"D:\\Softoo\\ML Task\\AI_Engine\\test_files\\sample.pptx.pptx\"\n",
    "    \n",
    "\n",
    "    file_path = ensure_file(SOURCE_FILE)\n",
    "\n",
    "    if file_path.suffix.lower() == \".csv\":\n",
    "        docs = load_csv(file_path)\n",
    "    else:\n",
    "        pdf_path = convert_to_pdf(file_path)\n",
    "        docs = list(iter_pdf_pages(pdf_path))\n",
    "\n",
    "    save_text(file_path.stem, docs)\n",
    "\n",
    "    logging.info(\"\\n================ DOCUMENT SUMMARY ================\\n\")\n",
    "    logging.info(f\"Processed on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\")\n",
    "    logging.info(f\"File Name: {file_path.name}\")\n",
    "    logging.info(f\"Directory: {file_path.resolve()}\")\n",
    "    logging.info(f\"Total Pages/Rows: {len(docs)}\")\n",
    "    logging.info(\"Status: Document Ready for processing\")\n",
    "    logging.info(\"\\n=================================================\\n\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
